image: openjdk:11

stages:
    - seed
    - seed_stage_2
    - test
    - checkstyle
    - jar

before_script:
    - cd FreshmanRPG
    - chmod +x ./gradlew

seed_GameServer:
    stage: seed
    script:
        - cd GameServer
        - ./../gradlew DBBuildQuestsAndObjectives
        - ./../gradlew DBBuildTestDBPlayers
        - ./../gradlew DBBuildTestLevels
        - ./../gradlew DBBuildTestQuestions
        - ./../gradlew DBBuildTestInteractableItems
        - ./../gradlew DBBuildTestVanityItems

seed_LoginServer: 
    stage: seed
    script:
        - cd LoginServer
        - ./../gradlew DBBuildTestDBPlayerLogin

seed_GameShared:
    stage: seed
    script:
        - cd GameShared
        - ./../gradlew DBBuildTestDBServers
        
seed_stage_2_GameServer:
    stage: seed_stage_2
    script:
        - cd GameServer
        - ./../gradlew DBBuildTestDoubloonPrizes
        - ./../gradlew DBBuildTestRandomFacts
        - ./../gradlew DBBuildTestDBVisitedMaps
        - ./../gradlew DBBuildFriends
        - ./../gradlew DBBuildTestVanityInventory
        - ./../gradlew DBBuildTestDefaultItems
        - ./../gradlew DBBuildTestVanityAwards
        - ./../gradlew DBBuildTestVanityShop

test_game_shared:
    stage: test
    artifacts:
        when: always
        paths:
            - GameShared/artifacts
    script:
        - cd GameShared
        - ./../gradlew test --tests "AllSharedTests"

test_login_server:
    stage: test
    artifacts:
        when: always
        paths:
            - LoginServer/artifacts
    script:
        - cd LoginServer
        - ./../gradlew test --tests "AllLoginServerTests"

test_game_server:
    stage: test
    artifacts:
        when: always
        paths:
            - GameServer/artifacts
    script:
        - cd GameServer
        - ./../gradlew test --tests "AllServerTests"

test_game_client:
    stage: test
    artifacts:
        when: always
        paths:
            - GameClient/artifacts
    script:
        - cd GameClient
        - ./../gradlew test --tests "AllClientTests"

test_game_sequence_tests:
    stage: test
    artifacts:
        when: always
        paths:
            - GameSequenceTests/artifacts
    script:
        - cd GameSequenceTests
        - ./../gradlew test --tests "model.SequenceTestRunner"

test_game_manager_tests:
    stage: test
    artifacts:
        when: always
        paths:
            - GameManager/artifacts
    script:
        - cd GameManager
        - ./../gradlew test --tests "AllManagerTests"

cs_gameClient:
    stage: checkstyle
    artifacts:
       when: always
    script:
        - cd GameClient
        - ./../gradlew checkstyleMain
        - ./../gradlew checkstyleTest

cs_gameClient-desktop:
    stage: checkstyle
    artifacts:
        when: always
    script:
        - cd GameClient-desktop
        - ./../gradlew checkstyleMain
        - ./../gradlew checkstyleTest

cs_gameManager:
    stage: checkstyle
    artifacts:
       when: always
    script:
        - cd GameManager
        - ./../gradlew checkstyleMain
        - ./../gradlew checkstyleTest

cs_gameSequenceTests:
    stage: checkstyle
    artifacts:
       when: always
    script:
        - cd GameSequenceTests
        - ./../gradlew checkstyleMain
        - ./../gradlew checkstyleTest

cs_gameServer:
    stage: checkstyle
    artifacts:
       when: always
    script:
        - cd GameServer
        - ./../gradlew checkstyleMain
        - ./../gradlew checkstyleTest

cs_gameShared:
    stage: checkstyle
    artifacts:
       when: always
    script:
        - cd GameShared
        - ./../gradlew checkstyleMain
        - ./../gradlew checkstyleTest

cs_loginServer:
    stage: checkstyle
    artifacts:
       when: always
    script:
        - cd LoginServer
        - ./../gradlew checkstyleMain
        - ./../gradlew checkstyleTest
