stages:
    - run
    - flutter

variables:
    DOCKER_DRIVER: overlay

.openjdk_docker_image:
    image: openjdk:17

.flutter_docker_image:
    image: cirrusci/flutter

run_pipeline:
    extends: .openjdk_docker_image
    stage: run
    artifacts:
        when: always
        reports:
            junit: FreshmanRPG/*/build/test-results/test/**/TEST-*.xml
        paths:
            - FreshmanRPG/*/*.log
    script:
        - cd FreshmanRPG
        - chmod +x ./gradlew
        - chmod +x ./test.sh
        - chmod +x ./setDatabase.sh
        - ./setDatabase.sh $CI_PIPELINE_ID
        - ./test.sh

game_manager_test:
    extends: .flutter_docker_image
    stage: flutter
    script:
        - cd game_manager
        - flutter test --coverage
        - genhtml coverage/lcov.info --output=coverage
    artifacts:
        paths:
            - coverage
        expire_in: 5 days

companion_app_test:
    extends: .flutter_docker_image
    stage: flutter
    script:
        - cd frpg-companion
        - flutter test --coverage
        - genhtml coverage/lcov.info --output=coverage
    artifacts:
        paths:
            - coverage
        expire_in: 5 days