image: openjdk:11

stages:
    - run

before_script:
    - cd FreshmanRPG
    - chmod +x ./gradlew
    - chmod +x ./runPipeline.sh
    - chmod +x ./setDatabase.sh

run_pipeline:
    stage: run
    script:
        - ./setDatabase.sh $CI_PIPELINE_ID
        - ./runPipeline.sh 
