image: openjdk:17

stages:
    - run

variables:
    DOCKER_DRIVER: overlay

before_script:
    - cd FreshmanRPG
    - chmod +x ./gradlew
    - chmod +x ./runPipeline.sh
    - chmod +x ./setDatabase.sh

run_pipeline:
    stage: run
    artifacts:
        when: always
        reports:
            junit: FreshmanRPG/*/build/test-results/test/**/TEST-*.xml
        paths:
            - FreshmanRPG/*/*.log
            
    script:
        - ./setDatabase.sh $CI_PIPELINE_ID
        - ./runPipeline.sh 
