---
version: "3.5"
services:
    frpg_mysql:
        container_name: frpg_mysql
        hostname: frpgmysql
        image: mysql:8.0
        restart: always
        build:
            context: ./database
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - frpgDB:/var/lib/mysql
        ports:
            - "127.0.0.1:3308:3306"
        networks:
            - frpg_database
        healthcheck:
            test: ["CMD", "mysqladmin", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 15s
#    frpg_login_server:
#        container_name: frpg_login_server
#        image: openjdk:11
#        restart: always
#        build:
#            context: ./login_server
#        volumes:
#            - ../FreshmanRPG:/repo/frpg:consistent
#        ports:
#            - "1871:1871"

volumes:
    frpgDB:

networks:
    frpg_database: