// Mocks generated by Mockito 5.3.2 from annotations
// in companion_app/test/pages/objectives-list/bloc/objectives_list_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:companion_app/repository/quests_objectives_repository/all-objectives-request.dart'
    as _i6;
import 'package:companion_app/repository/quests_objectives_repository/all-objectives-response.dart'
    as _i2;
import 'package:companion_app/repository/quests_objectives_repository/complete-objective-request.dart'
    as _i7;
import 'package:companion_app/repository/shared/general_response.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

import 'objectives_list_bloc_test.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAllObjectivesResponse_0 extends _i1.SmartFake
    implements _i2.AllObjectivesResponse {
  _FakeAllObjectivesResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeneralResponse_1 extends _i1.SmartFake
    implements _i3.GeneralResponse {
  _FakeGeneralResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [QuestsObjectivesRepositoryMock].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuestsObjectivesRepositoryMock extends _i1.Mock
    implements _i4.QuestsObjectivesRepositoryMock {
  MockQuestsObjectivesRepositoryMock() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.AllObjectivesResponse> getAllObjectives(
          _i6.AllObjectivesRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllObjectives,
          [request],
        ),
        returnValue: _i5.Future<_i2.AllObjectivesResponse>.value(
            _FakeAllObjectivesResponse_0(
          this,
          Invocation.method(
            #getAllObjectives,
            [request],
          ),
        )),
      ) as _i5.Future<_i2.AllObjectivesResponse>);
  @override
  _i5.Future<_i3.GeneralResponse> completeObjective(
          _i7.CompleteObjectiveRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeObjective,
          [request],
        ),
        returnValue:
            _i5.Future<_i3.GeneralResponse>.value(_FakeGeneralResponse_1(
          this,
          Invocation.method(
            #completeObjective,
            [request],
          ),
        )),
      ) as _i5.Future<_i3.GeneralResponse>);
}

/// A class which mocks [BarCodeScannerMock].
///
/// See the documentation for Mockito's code generation for more information.
class MockBarCodeScannerMock extends _i1.Mock
    implements _i4.BarCodeScannerMock {
  MockBarCodeScannerMock() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> scan() => (super.noSuchMethod(
        Invocation.method(
          #scan,
          [],
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
}
