// Mocks generated by Mockito 5.3.2 from annotations
// in companion_app/test/model/location_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:companion_app/model/location_utilities.dart' as _i3;
import 'package:companion_app/model/position_with_status.dart' as _i2;
import 'package:geolocator/geolocator.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePositionWithStatus_0 extends _i1.SmartFake
    implements _i2.PositionWithStatus {
  _FakePositionWithStatus_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GeoLocatorWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeoLocatorWrapper extends _i1.Mock implements _i3.GeoLocatorWrapper {
  MockGeoLocatorWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> isLocationEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isLocationEnabled,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<_i5.LocationPermission> checkPermission() => (super.noSuchMethod(
        Invocation.method(
          #checkPermission,
          [],
        ),
        returnValue: _i4.Future<_i5.LocationPermission>.value(
            _i5.LocationPermission.denied),
      ) as _i4.Future<_i5.LocationPermission>);
  @override
  _i4.Future<_i5.LocationPermission> requestPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestPermission,
          [],
        ),
        returnValue: _i4.Future<_i5.LocationPermission>.value(
            _i5.LocationPermission.denied),
      ) as _i4.Future<_i5.LocationPermission>);
  @override
  _i4.Future<_i2.PositionWithStatus> getCurrentPosition() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentPosition,
          [],
        ),
        returnValue:
            _i4.Future<_i2.PositionWithStatus>.value(_FakePositionWithStatus_0(
          this,
          Invocation.method(
            #getCurrentPosition,
            [],
          ),
        )),
      ) as _i4.Future<_i2.PositionWithStatus>);
  @override
  bool locationMatches(
    _i2.PositionWithStatus? location,
    double? qrLatitude,
    double? qrLongitude,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #locationMatches,
          [
            location,
            qrLatitude,
            qrLongitude,
          ],
        ),
        returnValue: false,
      ) as bool);
}
